### ISSUE TITLE
Game crashes upon use

### ISSUE THREAD

**Issue by TaylorAguilera** [withertech/Multiverse#1]
Hello! Not sure how else to get a hold of you. I found this mod through a popular mod pack on the Terraria subreddit. sounds like a pretty neat mod! However every time I try to the mirror, the window pops up with the worlds. when I click to transfer to the world, nothing happens, and when I remove the mirror the game crashes and resets the entire world.

Just wanted to ask how exactly does this mod works? How do I pack the subworld with the mod? Thank you very much!

**Comment by KP2048** [comment]
What version of the mod is it using?

**Comment by KP2048** [comment]
Some of the versions are kind of broken as this mod is wip

**Comment by KP2048** [comment]
If there is an update for multiverse, try and update. If not, let me know and I’ll send out a patch. Put a pastebin with the crash log so I can see what’s wrong

**Comment by KP2048** [comment]
Btw you cannot “pack” a subworld with the mod as they are world specific

**Comment by TaylorAguilera** [comment]
Hi! Sorry a response took so long!

So I am using Version 0.5 of Multiverse, there seems to be no update to it. I am using Tmod Loader 64 bit version V0.11.7.5. I cant seem to get an error message because it crashes immediately. Let me know if you have an idea on how I should proceed!

**Comment by KP2048** [comment]
There should be a log in Documents/my games/terraria/modloader/logs

**Comment by KP2048** [comment]
And multiverse is untested on 64 bit terraria as I don’t have it I have the steam one

**Comment by KP2048** [comment]
I have a big update I’m working on and a patch for that bug is included

**Comment by TaylorAguilera** [comment]
[client.log](https://github.com/withertech/Multiverse/files/5258701/client.log)

Got it. Here is a log that has the error. Hope it helps!

**Comment by KP2048** [comment]
It’s not finding the enter method. Typo maybe?
I’ll take a look

**Comment by KP2048** [comment]
No typo

**Comment by KP2048** [comment]
What version of sublib are you using?

**Comment by KP2048** [comment]
Try updating it

**Comment by KP2048** [comment]
Btw this mod does not currently work in multiplayer so if you are in multiplayer it will crash

**Comment by TaylorAguilera** [comment]
No i am not using it with Multiplayer. I am using V1.1.0.3 of SubWorld Library

**Comment by KP2048** [comment]
This is very strange! I’m using the same sublib version

**Comment by KP2048** [comment]
I reverted to the latest mod browser version and can confirm this bug exists on that version and is patched in the next version

**Comment by KP2048** [comment]
I will release it shortly

**Comment by KP2048** [comment]
Released!

**Comment by KP2048** [comment]
You cannot “pack” a subworld with the mod. However, the default subworlds are defined in the mod’s Config and if you have any suggestions for world types I’m open!

**Comment by KP2048** [comment]
If you want to include a subworld with a mod pack, the subworlds are stored in Documents/my games/terraria/modloader/worlds/subworlds/(WorldName)/multiverse_(subworld name).(twld/wld)

**Comment by KP2048** [comment]
You can include the subworld(s) in the download and instructions on where to put it

**Comment by KP2048** [comment]
Just make sure the subworld exists in the mod Config or give them a Config where it does

**Comment by TaylorAguilera** [comment]
thanks for the help! Works fine now!
